services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_state:/root/.ollama

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8910 --reload
    environment:
      - JINA_API_KEY=${JINA_API_KEY}
      - QDRANT_URL=http://qdrant:6333
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_MODEL=deepseek-r1:7b
      - ENABLE_WEB_SEARCH=1
    ports:
      - "8910:8910"
    volumes:
      - ${PWD}/data:/data
      - ${PWD}/data/raw:/workspace/documents
    depends_on:
      - qdrant
      - ollama
    restart: unless-stopped

  ingestor:
    build:
      context: .
      dockerfile: Dockerfile.api
    command: python -m src.scripts.ingest --data_dir /data/raw --collection aegis_docs
    environment:
      - JINA_API_KEY=${JINA_API_KEY}
      - QDRANT_URL=http://qdrant:6333
    volumes:
      - ${PWD}/data:/data
    depends_on:
      - qdrant
    # This service runs once to ingest data and then exits.
    # It won't be restarted unless you manually run `docker compose up ingestor`.
    restart: 'no'



  openwebui:
    image: dyrnq/open-webui:latest
    restart: unless-stopped
    ports:
      - "8920:8080"
    volumes:
      - open_webui_data:/app/backend/data
      - ${PWD}/data/raw:/workspace/documents
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - 'OPENAI_BASE_URLS=http://api:8910/v1'
      - WEBUI_PLUGINS=supreme_file_management
      - UPLOAD_DIR=/workspace/documents
    depends_on:
      - ollama
      - api

volumes:
  qdrant_data: 
  ollama_state: 
  open_webui_data: 