services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_state:/root/.ollama

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    command: uvicorn app:app --host 0.0.0.0 --port 8910 --reload
    environment:
      - JINA_API_KEY=${JINA_API_KEY}
      - QDRANT_URL=http://qdrant:6333
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_MODEL=deepseek-r1:7b
    ports:
      - "8910:8910"
    volumes:
      - ${PWD}/data:/data
    depends_on:
      - qdrant
      - ollama
    restart: unless-stopped

  ingestor:
    build:
      context: .
      dockerfile: Dockerfile.api
    command: python ingest.py
    environment:
      - JINA_API_KEY=${JINA_API_KEY}
      - QDRANT_URL=http://qdrant:6333
    volumes:
      - ${PWD}/data:/data
    depends_on:
      - qdrant
    # This service runs once to ingest data and then exits.
    # It won't be restarted unless you manually run `docker compose up ingestor`.
    restart: 'no'

  # Удаляем устаревший сервис UI
  # ui:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.ui
  #   ports:
  #     - "8920:80"
  #   environment:
  #     - VITE_API=http://api:8910
  #   depends_on:
  #     - api

  openwebui:
    image: dyrnq/open-webui:latest
    restart: unless-stopped
    ports:
      - "8920:8080"
    volumes:
      - open_webui_data:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - 'OPENAI_BASE_URLS=http://api:8910/v1'
    depends_on:
      - ollama
      - api

volumes:
  qdrant_data: 
  ollama_state: 
  open_webui_data: 