version: '3.9'

services:
  qdrant:
    image: qdrant/qdrant:v1.8.3
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8910 --reload
    env_file:
      - .env
    depends_on:
      - qdrant
    ports:
      - "8910:8910"
    volumes:
      - ./:/app

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    depends_on:
      - api
    ports:
      - "8920:80"
    environment:
      - VITE_API=http://api:8910

  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    environment:
      - OLLAMA_MODELS=llama3
    ports:
      - "11434:11434"
    volumes:
      - ollama_state:/root/.ollama

volumes:
  qdrant_data:
  ollama_state: 