version: '3.9'

services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/healthz"]
      interval: 5s
      timeout: 3s
      retries: 3

  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_state:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    command: uvicorn app:app --host 0.0.0.0 --port 8910 --reload
    env_file: .env
    ports:
      - "8910:8910"
    volumes:
      - ./data:/app/data
      - ./app.py:/app/app.py # Mount for hot-reloading
    depends_on:
      qdrant:
        condition: service_healthy
      ollama:
        condition: service_healthy
    restart: unless-stopped

  ingestor:
    build:
      context: .
      dockerfile: Dockerfile.api
    command: python ingest.py
    env_file: .env
    volumes:
      - ./data:/app/data
    depends_on:
      qdrant:
        condition: service_healthy
    # This service runs once to ingest data and then exits.
    # It won't be restarted unless you manually run `docker compose up ingestor`.
    restart: 'no'

  ui:
    build:
      context: ./simple # Assuming UI code is in the simple folder now
      dockerfile: Dockerfile.ui
    ports:
      - "8920:80"
    environment:
      - VITE_API=http://api:8910
    depends_on:
      - api

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - qdrant
      - ui
      - api
    restart: unless-stopped

volumes:
  qdrant_data:
  ollama_state: 